/*
 * Geforce NV2A PGRAPH GLSL combiner ubershader
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#include "qemu/osdep.h"

#include "psh-uber.h"

void pgraph_glsl_append_psh_uber_declarations(MString *source, int binding)
{
    mstring_append_fmt(
        source,
        "layout(binding = %d, std140) uniform PshUberControls {\n"
        "    uvec4 uberHeader;\n"
        "    uvec4 uberStage[8];\n"
        "    uvec4 uberFinal;\n"
        "    vec4 uberConstants[18];\n"
        "};\n"
        "vec3 uberMapInput3(vec3 value, uint code) {\n"
        "    switch (code & 0xe0u) {\n"
        "    case 0x00u: return max(value, vec3(0.0));\n"
        "    case 0x20u: return vec3(1.0) - clamp(value, vec3(0.0), vec3(1.0));\n"
        "    case 0x40u: return 2.0 * max(value, vec3(0.0)) - vec3(1.0);\n"
        "    case 0x60u: return vec3(1.0) - 2.0 * max(value, vec3(0.0));\n"
        "    case 0x80u: return max(value, vec3(0.0)) - vec3(0.5);\n"
        "    case 0xa0u: return vec3(0.5) - max(value, vec3(0.0));\n"
        "    case 0xc0u: return value;\n"
        "    default: return -value;\n"
        "    }\n"
        "}\n"
        "float uberMapInput1(float value, uint code) {\n"
        "    switch (code & 0xe0u) {\n"
        "    case 0x00u: return max(value, 0.0);\n"
        "    case 0x20u: return 1.0 - clamp(value, 0.0, 1.0);\n"
        "    case 0x40u: return 2.0 * max(value, 0.0) - 1.0;\n"
        "    case 0x60u: return 1.0 - 2.0 * max(value, 0.0);\n"
        "    case 0x80u: return max(value, 0.0) - 0.5;\n"
        "    case 0xa0u: return 0.5 - max(value, 0.0);\n"
        "    case 0xc0u: return value;\n"
        "    default: return -value;\n"
        "    }\n"
        "}\n"
        "vec3 uberMapOutput3(vec3 value, uint flags) {\n"
        "    switch (flags & 0x38u) {\n"
        "    case 0x00u: return value;\n"
        "    case 0x08u: return value - vec3(0.5);\n"
        "    case 0x10u: return value * 2.0;\n"
        "    case 0x18u: return (value - vec3(0.5)) * 2.0;\n"
        "    case 0x20u: return value * 4.0;\n"
        "    default: return value * 0.5;\n"
        "    }\n"
        "}\n"
        "float uberMapOutput1(float value, uint flags) {\n"
        "    switch (flags & 0x38u) {\n"
        "    case 0x00u: return value;\n"
        "    case 0x08u: return value - 0.5;\n"
        "    case 0x10u: return value * 2.0;\n"
        "    case 0x18u: return (value - 0.5) * 2.0;\n"
        "    case 0x20u: return value * 4.0;\n"
        "    default: return value * 0.5;\n"
        "    }\n"
        "}\n"
        "vec4 uberRead(uint code, uint stage, vec4 regs[16], vec4 ef) {\n"
        "    uint reg = code & 0x0fu;\n"
        "    if (reg == 1u || reg == 2u) {\n"
        "        uint unique = reg == 1u ? 0x10u : 0x100u;\n"
        "        uint base = (stage == 8u || ((uberHeader.z >> 8u) & unique) != 0u) ? stage * 2u : 0u;\n"
        "        return uberConstants[base + reg - 1u];\n"
        "    }\n"
        "    if (reg == 14u) {\n"
        "        vec3 left = (uberFinal.y & 0x40u) != 0u ? vec3(1.0) - regs[5].rgb : regs[5].rgb;\n"
        "        vec3 right = (uberFinal.y & 0x20u) != 0u ? vec3(1.0) - regs[12].rgb : regs[12].rgb;\n"
        "        vec3 sum = left + right;\n"
        "        if ((uberFinal.y & 0x80u) != 0u) sum = clamp(sum, vec3(0.0), vec3(1.0));\n"
        "        return vec4(sum, 0.0);\n"
        "    }\n"
        "    if (reg == 15u) return ef;\n"
        "    return regs[reg];\n"
        "}\n"
        "vec3 uberInput3(uint code, uint stage, vec4 regs[16], vec4 ef) {\n"
        "    vec4 value = uberRead(code, stage, regs, ef);\n"
        "    return uberMapInput3((code & 0x10u) != 0u ? value.aaa : value.rgb, code);\n"
        "}\n"
        "float uberInput1(uint code, uint stage, vec4 regs[16], vec4 ef) {\n"
        "    vec4 value = uberRead(code, stage, regs, ef);\n"
        "    return uberMapInput1((code & 0x10u) != 0u ? value.a : value.b, code);\n"
        "}\n"
        "void uberWriteRGB(inout vec4 regs[16], uint reg, vec3 value, bool blueToAlpha) {\n"
        "    if (reg == 0u) return;\n"
        "    regs[reg].rgb = value;\n"
        "    if (blueToAlpha) regs[reg].a = value.b;\n"
        "}\n"
        "void uberWriteAlpha(inout vec4 regs[16], uint reg, float value) {\n"
        "    if (reg != 0u) regs[reg].a = value;\n"
        "}\n",
        binding);
}

void pgraph_glsl_append_psh_uber_body(MString *source,
                                      bool texture_stage_zero_active)
{
    mstring_append_fmt(
        source,
        "vec4 uberRegs[16];\n"
        "for (uint uberReg = 0u; uberReg < 16u; uberReg++) uberRegs[uberReg] = vec4(0.0);\n"
        "uberRegs[3] = pFog;\n"
        "uberRegs[4] = v0; uberRegs[5] = v1;\n"
        "uberRegs[8] = t0; uberRegs[9] = t1; uberRegs[10] = t2; uberRegs[11] = t3;\n"
        "uberRegs[12].a = %s;\n"
        "uint uberStageCount = min(uberHeader.y, 8u);\n"
        "for (uint uberIndex = 0u; uberIndex < uberStageCount; uberIndex++) {\n"
        "    uvec4 uberWords = uberStage[uberIndex];\n"
        "    vec4 uberOldR0 = uberRegs[12];\n"
        "    vec3 uberRA = uberInput3((uberWords.x >> 24u) & 0xffu, uberIndex, uberRegs, vec4(0.0));\n"
        "    vec3 uberRB = uberInput3((uberWords.x >> 16u) & 0xffu, uberIndex, uberRegs, vec4(0.0));\n"
        "    vec3 uberRC = uberInput3((uberWords.x >> 8u) & 0xffu, uberIndex, uberRegs, vec4(0.0));\n"
        "    vec3 uberRD = uberInput3(uberWords.x & 0xffu, uberIndex, uberRegs, vec4(0.0));\n"
        "    uint uberRFlags = uberWords.z >> 12u;\n"
        "    vec3 uberRABRaw = (uberRFlags & 0x02u) != 0u ? vec3(dot(uberRA, uberRB)) : uberRA * uberRB;\n"
        "    vec3 uberRCDRaw = (uberRFlags & 0x01u) != 0u ? vec3(dot(uberRC, uberRD)) : uberRC * uberRD;\n"
        "    vec3 uberRMuxRaw = (uberRFlags & 0x04u) != 0u ? (uberOldR0.a >= 0.5 ? uberRCDRaw : uberRABRaw) : uberRABRaw + uberRCDRaw;\n"
        "    vec3 uberRAB = clamp(uberMapOutput3(uberRABRaw, uberRFlags), vec3(-1.0), vec3(1.0));\n"
        "    vec3 uberRCD = clamp(uberMapOutput3(uberRCDRaw, uberRFlags), vec3(-1.0), vec3(1.0));\n"
        "    vec3 uberRMux = clamp(uberMapOutput3(uberRMuxRaw, uberRFlags), vec3(-1.0), vec3(1.0));\n"
        "    float uberAA = uberInput1((uberWords.y >> 24u) & 0xffu, uberIndex, uberRegs, vec4(0.0));\n"
        "    float uberAB = uberInput1((uberWords.y >> 16u) & 0xffu, uberIndex, uberRegs, vec4(0.0));\n"
        "    float uberAC = uberInput1((uberWords.y >> 8u) & 0xffu, uberIndex, uberRegs, vec4(0.0));\n"
        "    float uberAD = uberInput1(uberWords.y & 0xffu, uberIndex, uberRegs, vec4(0.0));\n"
        "    uint uberAFlags = uberWords.w >> 12u;\n"
        "    float uberAABRaw = uberAA * uberAB;\n"
        "    float uberACDRaw = uberAC * uberAD;\n"
        "    float uberAMuxRaw = (uberAFlags & 0x04u) != 0u ? (uberOldR0.a >= 0.5 ? uberACDRaw : uberAABRaw) : uberAABRaw + uberACDRaw;\n"
        "    float uberAAB = clamp(uberMapOutput1(uberAABRaw, uberAFlags), -1.0, 1.0);\n"
        "    float uberACD = clamp(uberMapOutput1(uberACDRaw, uberAFlags), -1.0, 1.0);\n"
        "    float uberAMux = clamp(uberMapOutput1(uberAMuxRaw, uberAFlags), -1.0, 1.0);\n"
        "    uberWriteRGB(uberRegs, (uberWords.z >> 4u) & 0x0fu, uberRAB, (uberRFlags & 0x80u) != 0u);\n"
        "    uberWriteRGB(uberRegs, uberWords.z & 0x0fu, uberRCD, (uberRFlags & 0x40u) != 0u);\n"
        "    uberWriteRGB(uberRegs, (uberWords.z >> 8u) & 0x0fu, uberRMux, false);\n"
        "    uberWriteAlpha(uberRegs, (uberWords.w >> 4u) & 0x0fu, uberAAB);\n"
        "    uberWriteAlpha(uberRegs, uberWords.w & 0x0fu, uberACD);\n"
        "    uberWriteAlpha(uberRegs, (uberWords.w >> 8u) & 0x0fu, uberAMux);\n"
        "}\n"
        "vec3 uberE = uberInput3((uberFinal.y >> 24u) & 0xffu, 8u, uberRegs, vec4(0.0));\n"
        "vec3 uberF = uberInput3((uberFinal.y >> 16u) & 0xffu, 8u, uberRegs, vec4(0.0));\n"
        "vec4 uberEF = vec4(uberE * uberF, 0.0);\n"
        "vec3 uberA = uberInput3((uberFinal.x >> 24u) & 0xffu, 8u, uberRegs, uberEF);\n"
        "vec3 uberB = uberInput3((uberFinal.x >> 16u) & 0xffu, 8u, uberRegs, uberEF);\n"
        "vec3 uberC = uberInput3((uberFinal.x >> 8u) & 0xffu, 8u, uberRegs, uberEF);\n"
        "vec3 uberD = uberInput3(uberFinal.x & 0xffu, 8u, uberRegs, uberEF);\n"
        "float uberGValue = uberInput1((uberFinal.y >> 8u) & 0xffu, 8u, uberRegs, uberEF);\n"
        "vec4 uberG = vec4(uberGValue);\n"
        "fragColor.rgb = uberD.rgb + mix(uberC.rgb, uberB.rgb, uberA.rgb);\n"
        "fragColor.a = uberG.a;\n",
        texture_stage_zero_active ? "t0.a" : "1.0");
}
