name: Copy External Branch

on:
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo
        uses: actions/checkout@v4
        with:
          repository: player1byd/xemu
          ref: master
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Fetch external branch
        run: |
          git remote add external https://github.com/Tovarichtch/xemu.git
          git fetch external perf-experimental
          git checkout -B perf-experimental external/perf-experimental

      - name: Push
        run: git push origin perf-experimental
