name: Copy External Branch

on:
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout external branch
        uses: actions/checkout@v4
        with:
          repository: Tovarichtch/xemu
          ref: perf-experimental
          fetch-depth: 0

      - name: Push to my repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add mine https://x-access-token:${GITHUB_TOKEN}@github.com/player1byd/xemu.git
          git push mine HEAD:refs/heads/perf-experimental
